name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout repo
      run: git clone https://github.com/envoyproxy/envoy.git
    - name: Run a multi-line script
      run: |
        cd envoy
        ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
